# Generated by Django 5.1.2 on 2024-11-02 01:51

import django.core.validators
import django.db.models.deletion
import ecommerce.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresarial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=ecommerce.utils.rename_image)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=15)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(default=None, max_length=2)),
                ('usuarios', models.ManyToManyField(related_name='enderecos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_responsavel', models.CharField(default=None, max_length=100)),
                ('cpf_responsavel', models.CharField(default=None, max_length=15)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(default=None, max_length=20)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=ecommerce.utils.rename_image)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.endereco')),
                ('lojista', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresarial.lojista')),
                ('plano', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresarial.plano')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True)),
                ('avaliacoes', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=ecommerce.utils.rename_image)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.loja')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=100)),
                ('conteudo', models.TextField()),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('recomenda', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
