# Generated by Django 5.1.2 on 2024-10-24 11:32

import ecommerce.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.utils.rename_image),
        ),
    ]
