# Generated by Django 5.1.2 on 2024-10-24 13:05

import ecommerce.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_produto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.utils.rename_image),
        ),
    ]
