# Generated by Django 5.1.2 on 2024-10-24 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_loja_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='CNPJ inválido', regex='^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='loja',
            name='ie',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='IE inválida', regex='^\\d{9}$')]),
        ),
    ]
