# Generated by Django 5.1.2 on 2024-10-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_categoria_produto_id_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_loja',
            new_name='loja',
        ),
    ]
