# Generated by Django 5.1.2 on 2024-10-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_id_categoria_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loja',
            name='ie',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
