# Generated by Django 5.1.2 on 2024-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_endereco_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
