# Generated by Django 5.1.2 on 2024-10-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_endereco_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='loja',
            name='ie',
            field=models.CharField(max_length=12),
        ),
    ]
