# Generated by Django 5.1.2 on 2024-11-12 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_produto_altura_produto_comprimento_produto_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelecaoEnderecoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.endereco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
