# Generated by Django 5.1.2 on 2024-10-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_loja_cnpj_alter_loja_ie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
