# Generated by Django 5.1.2 on 2024-11-15 21:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='desconto',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.04), django.core.validators.MaxValueValidator(0.16)]),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('crédito', 'Crédito'), ('pix', 'Pix')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('em andamento', 'Em Andamento'), ('saiu para entrega', 'Saiu para entrega'), ('finalizado', 'Finalizado'), ('abandonado', 'Abandonado'), ('cancelado', 'Cancelado'), ('entregue', 'Entregue')], default='em andamento', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.carrinho')),
                ('endereco_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.endereco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
