# Generated by Django 5.1.2 on 2024-10-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_datetime_submited_avaliacao_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
