# Generated by Django 5.1.2 on 2024-11-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_pedido_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('crédito', 'Crédito'), ('pix', 'Pix')], default=None, max_length=20, null=True),
        ),
    ]
