# Generated by Django 5.1.2 on 2024-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em andamento', 'Em Andamento'), ('confirmado', 'Confirmado'), ('abandonado', 'Abandonado'), ('cancelado', 'Cancelado'), ('entregue', 'Entregue')], default='em andamento', max_length=20),
        ),
    ]
