# Generated by Django 5.1.2 on 2024-12-03 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_pedido_status_avaliacaoloja_avaliacaomotorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoloja',
            name='nota',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
