# Generated by Django 5.1.2 on 2024-11-15 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_cupom_desconto_pedido'),
        ('entregas', '0002_motorista_is_staff_motorista_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('expressa', 'Expressa'), ('agendada', 'Agendada')], default=None, max_length=20)),
                ('entrega_pelo_app', models.BooleanField()),
                ('taxa_de_entrega', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('a caminho da loja', 'A caminho da loja'), ('saiu para entrega', 'Saiu para entrega'), ('cancelada', 'Cancelada'), ('entregue', 'Entregue')], max_length=20)),
                ('endereco_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.endereco')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.motorista')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaAgendada',
            fields=[
                ('entrega_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entregas.entrega')),
            ],
            bases=('entregas.entrega',),
        ),
    ]
