# Generated by Django 5.1.2 on 2024-11-17 00:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_entrega_entregaagendada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='tipo_entrega',
            new_name='forma_de_entrega',
        ),
        migrations.AddField(
            model_name='entregaagendada',
            name='datetime_entrega',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='entrega_pelo_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='motorista',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.motorista'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('preparando o pedido', 'Preparando o pedido'), ('a caminho da loja', 'A caminho da loja'), ('saiu para entrega', 'Saiu para entrega'), ('cancelada', 'Cancelada'), ('entregue', 'Entregue')], default='preparando o pedido', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='taxa_de_entrega',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
