# Generated by Django 5.1.2 on 2024-11-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_alter_entrega_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='forma_de_entrega',
            field=models.CharField(choices=[('expressa', 'Expressa'), ('agendada', 'Agendada')], default='expressa', max_length=20),
        ),
    ]
