# Generated by Django 5.1.2 on 2024-11-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0006_alter_entrega_forma_de_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='motorista',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.motorista'),
        ),
    ]
