# Generated by Django 5.1.2 on 2024-12-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0008_motorista_entregas_aceitas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='entregas_canceladas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EntregaCanceladaPeloMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.entrega')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.motorista')),
            ],
        ),
    ]
