# Generated by Django 5.1.2 on 2024-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0009_motorista_entregas_canceladas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='entregas_aceitas',
            new_name='entregas_realizadas',
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('aguardando confirmação da loja', 'Aguardando confirmação da loja'), ('preparando o pedido', 'Preparando o pedido'), ('pedido preparado', 'Pedido preparado'), ('a caminho da loja', 'A caminho da loja'), ('saiu para entrega', 'Saiu para entrega'), ('cancelada', 'Cancelada'), ('entregue', 'Entregue')], default='aguardando confirmação da loja', max_length=50),
        ),
    ]
