# Generated by Django 5.1.2 on 2024-12-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0010_rename_entregas_aceitas_motorista_entregas_realizadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='avaliou',
            field=models.BooleanField(default=False),
        ),
    ]
