# Generated by Django 5.1.2 on 2024-11-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Basico', 'Plano Básico'), ('Entrega', 'Plano Entrega')], max_length=10)),
                ('comissao', models.DecimalField(decimal_places=3, max_digits=5)),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_pagamento_pelo_app', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
