# Generated by Django 5.1.2 on 2024-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojista',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lojista',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
