# Generated by Django 5.1.2 on 2024-12-03 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_avaliacaoloja_nota'),
        ('empresarial', '0002_lojista_is_staff_lojista_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaLojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.avaliacao')),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresarial.lojista')),
            ],
        ),
    ]
